package gcpgrlx

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func RenderRecipe(cfg Config) (string, error) {
	cfg.setDefaults()
	if err := cfg.Validate(); err != nil {
		return "", err
	}

	var builder strings.Builder
	builder.WriteString("name: gcpgrlx-cloud-run-deploy\n")
	builder.WriteString("description: |\n")
	builder.WriteString(fmt.Sprintf("  Generated by gcpgrlx for project %s in %s.\n", cfg.ProjectID, cfg.Region))
	builder.WriteString("states:\n")

	appendDirectoryState(&builder, "Ensure deployment workspace exists", cfg.DeploymentRoot)
	appendCmdState(&builder, "Verify gcloud is installed", "gcloud version", []string{
		"CLOUDSDK_CORE_DISABLE_PROMPTS=1",
	}, "2m")

	enableCommand := fmt.Sprintf(
		"gcloud services enable %s --project %s",
		strings.Join(cfg.SortedRequiredServices(), " "),
		shellQuote(cfg.ProjectID),
	)
	appendCmdState(&builder, "Enable required GCP APIs", enableCommand, []string{
		"CLOUDSDK_CORE_DISABLE_PROMPTS=1",
	}, "20m")

	repoCommand := fmt.Sprintf(
		"bash -lc %s",
		shellQuote(fmt.Sprintf(
			"gcloud artifacts repositories describe %s --location %s --project %s >/dev/null 2>&1 || gcloud artifacts repositories create %s --repository-format docker --location %s --description 'Managed by gcpgrlx' --project %s",
			cfg.ArtifactRegistryRepository,
			cfg.Region,
			cfg.ProjectID,
			cfg.ArtifactRegistryRepository,
			cfg.Region,
			cfg.ProjectID,
		)),
	)
	appendCmdState(&builder, "Ensure Artifact Registry repository exists", repoCommand, []string{
		"CLOUDSDK_CORE_DISABLE_PROMPTS=1",
	}, "20m")

	for _, service := range cfg.Services {
		command := renderDeployCommand(cfg, service)
		appendCmdState(&builder, fmt.Sprintf("Deploy %s", service.Name), command, []string{
			"CLOUDSDK_CORE_DISABLE_PROMPTS=1",
		}, "30m")
	}

	return builder.String(), nil
}

func WriteRecipeFile(cfg Config, outDir string) (string, error) {
	recipe, err := RenderRecipe(cfg)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", fmt.Errorf("create output directory: %w", err)
	}
	path := filepath.Join(outDir, "deploy.grlx")
	if err := os.WriteFile(path, []byte(recipe), 0o644); err != nil {
		return "", fmt.Errorf("write recipe: %w", err)
	}
	return path, nil
}

func renderDeployCommand(cfg Config, service Service) string {
	parts := []string{
		"gcloud", "run", "deploy", shellQuote(service.Name),
		"--project", shellQuote(cfg.ProjectID),
		"--region", shellQuote(cfg.Region),
		"--platform", "managed",
		"--image", shellQuote(service.Image),
		"--port", strconv.Itoa(service.Port),
		"--cpu", shellQuote(service.CPU),
		"--memory", shellQuote(service.Memory),
		"--min-instances", strconv.Itoa(service.MinInstances),
		"--max-instances", strconv.Itoa(service.MaxInstances),
		"--timeout", shellQuote(service.Timeout),
		"--ingress", shellQuote(service.Ingress),
	}

	if service.ServiceAccount != "" {
		parts = append(parts, "--service-account", shellQuote(service.ServiceAccount))
	}

	if service.AllowUnauthenticated != nil {
		if *service.AllowUnauthenticated {
			parts = append(parts, "--allow-unauthenticated")
		} else {
			parts = append(parts, "--no-allow-unauthenticated")
		}
	}

	if len(service.Env) > 0 {
		values := make([]string, 0, len(service.Env))
		for _, key := range service.SortedEnvKeys() {
			values = append(values, fmt.Sprintf("%s=%s", key, service.Env[key]))
		}
		parts = append(parts, "--set-env-vars", shellQuote(strings.Join(values, ",")))
	}

	if len(service.Labels) > 0 {
		values := make([]string, 0, len(service.Labels))
		for _, key := range service.SortedLabelKeys() {
			values = append(values, fmt.Sprintf("%s=%s", key, service.Labels[key]))
		}
		parts = append(parts, "--labels", shellQuote(strings.Join(values, ",")))
	}

	return strings.Join(parts, " ")
}

func appendCmdState(builder *strings.Builder, title string, command string, env []string, timeout string) {
	builder.WriteString(fmt.Sprintf("  - name: %s\n", yamlScalar(title)))
	builder.WriteString("    cmd.run:\n")
	builder.WriteString(fmt.Sprintf("      - name: %s\n", yamlScalar(command)))
	if len(env) > 0 {
		builder.WriteString("        env:\n")
		for _, entry := range env {
			builder.WriteString(fmt.Sprintf("          - %s\n", yamlScalar(entry)))
		}
	}
	if timeout != "" {
		builder.WriteString(fmt.Sprintf("        timeout: %s\n", yamlScalar(timeout)))
	}
}

func appendDirectoryState(builder *strings.Builder, title string, path string) {
	builder.WriteString(fmt.Sprintf("  - name: %s\n", yamlScalar(title)))
	builder.WriteString("    file.directory:\n")
	builder.WriteString(fmt.Sprintf("      - name: %s\n", yamlScalar(path)))
	builder.WriteString("        makedirs: true\n")
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func yamlScalar(value string) string {
	return strconv.Quote(value)
}
