package gcpgrlx

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type planStep struct {
	Title   string
	Kind    string
	Target  string
	Command string
}

func RenderRecipe(cfg Config) (string, error) {
	cfg.setDefaults()
	if err := cfg.Validate(); err != nil {
		return "", err
	}

	var builder strings.Builder
	builder.WriteString("name: gcpgrlx-cloud-run-deploy\n")
	builder.WriteString("description: |\n")
	builder.WriteString(fmt.Sprintf("  Generated by gcpgrlx for project %s in %s.\n", cfg.ProjectID, cfg.Region))
	builder.WriteString("states:\n")

	for _, step := range buildPlanSteps(cfg) {
		switch step.Kind {
		case "directory":
			appendDirectoryState(&builder, step.Title, step.Target)
		case "command":
			appendCmdState(&builder, step.Title, step.Command, []string{
				"CLOUDSDK_CORE_DISABLE_PROMPTS=1",
			}, planStepTimeout(step.Title))
		default:
			return "", fmt.Errorf("unsupported plan step kind: %s", step.Kind)
		}
	}

	return builder.String(), nil
}

func RenderPlan(cfg Config) (string, error) {
	cfg.setDefaults()
	if err := cfg.Validate(); err != nil {
		return "", err
	}

	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("Plan for project %s in %s\n", cfg.ProjectID, cfg.Region))

	for index, step := range buildPlanSteps(cfg) {
		builder.WriteString(fmt.Sprintf("%d. %s\n", index+1, step.Title))
		switch step.Kind {
		case "directory":
			builder.WriteString(fmt.Sprintf("   file.directory %s\n", step.Target))
		case "command":
			builder.WriteString(fmt.Sprintf("   %s\n", step.Command))
		default:
			return "", fmt.Errorf("unsupported plan step kind: %s", step.Kind)
		}
	}

	return builder.String(), nil
}

func WriteRecipeFile(cfg Config, outDir string) (string, error) {
	recipe, err := RenderRecipe(cfg)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", fmt.Errorf("create output directory: %w", err)
	}
	path := filepath.Join(outDir, "deploy.grlx")
	if err := os.WriteFile(path, []byte(recipe), 0o644); err != nil {
		return "", fmt.Errorf("write recipe: %w", err)
	}
	return path, nil
}

func buildPlanSteps(cfg Config) []planStep {
	enableCommand := fmt.Sprintf(
		"gcloud services enable %s --project %s",
		strings.Join(cfg.SortedRequiredServices(), " "),
		shellQuote(cfg.ProjectID),
	)

	repoCommand := fmt.Sprintf(
		"bash -lc %s",
		shellQuote(fmt.Sprintf(
			"gcloud artifacts repositories describe %s --location %s --project %s >/dev/null 2>&1 || gcloud artifacts repositories create %s --repository-format docker --location %s --description 'Managed by gcpgrlx' --project %s",
			cfg.ArtifactRegistryRepository,
			cfg.Region,
			cfg.ProjectID,
			cfg.ArtifactRegistryRepository,
			cfg.Region,
			cfg.ProjectID,
		)),
	)

	steps := []planStep{
		{Title: "Ensure deployment workspace exists", Kind: "directory", Target: cfg.DeploymentRoot},
		{Title: "Verify gcloud is installed", Kind: "command", Command: "gcloud version"},
		{Title: "Enable required GCP APIs", Kind: "command", Command: enableCommand},
		{Title: "Ensure Artifact Registry repository exists", Kind: "command", Command: repoCommand},
	}

	// Each service becomes one deploy step, plus an optional traffic step when rollout control is requested.
	for _, service := range cfg.Services {
		steps = append(steps, planStep{
			Title:   fmt.Sprintf("Deploy %s", service.Name),
			Kind:    "command",
			Command: renderDeployCommand(cfg, service),
		})
		if command := renderTrafficCommand(cfg, service); command != "" {
			steps = append(steps, planStep{
				Title:   fmt.Sprintf("Update traffic for %s", service.Name),
				Kind:    "command",
				Command: command,
			})
		}
	}

	return steps
}

func planStepTimeout(title string) string {
	switch {
	case strings.HasPrefix(title, "Verify gcloud"):
		return "2m"
	case strings.HasPrefix(title, "Update traffic"):
		return "10m"
	case strings.HasPrefix(title, "Deploy "):
		return "30m"
	default:
		return "20m"
	}
}

func renderDeployCommand(cfg Config, service Service) string {
	parts := deployBaseCommand(cfg, service)
	parts = appendStringFlag(parts, "--command", service.Command)
	parts = appendJoinedFlag(parts, "--args", service.Args)
	parts = appendStringFlag(parts, "--service-account", service.ServiceAccount)
	parts = appendStringFlag(parts, "--revision-suffix", service.RevisionSuffix)
	parts = appendToggleFlag(parts, service.AllowUnauthenticated, "--allow-unauthenticated", "--no-allow-unauthenticated")
	parts = appendToggleFlag(parts, service.UseHTTP2, "--use-http2", "--no-use-http2")
	parts = appendToggleFlag(parts, service.CPUThrottling, "--cpu-throttling", "--no-cpu-throttling")
	parts = appendToggleFlag(parts, service.StartupCPUBoost, "--startup-cpu-boost", "--no-startup-cpu-boost")
	parts = appendFlagIf(parts, service.NoTraffic, "--no-traffic")
	parts = appendStringFlag(parts, "--vpc-connector", service.VPCConnector)
	parts = appendStringFlag(parts, "--vpc-egress", service.VPCEgress)
	parts = appendJoinedFlag(parts, "--add-cloudsql-instances", service.CloudSQLInstances)
	parts = appendSecretsFlag(parts, service)
	parts = appendKeyValueFlag(parts, "--set-env-vars", service.SortedEnvKeys(), service.Env)
	parts = appendKeyValueFlag(parts, "--labels", service.SortedLabelKeys(), service.Labels)
	parts = appendKeyValueFlag(parts, "--update-annotations", service.SortedAnnotationKeys(), service.Annotations)
	parts = appendProbeFlags(parts, "startup", service.StartupProbe)
	parts = appendProbeFlags(parts, "liveness", service.LivenessProbe)

	return strings.Join(parts, " ")
}

func renderTrafficCommand(cfg Config, service Service) string {
	// Traffic shaping is a second step because Cloud Run manages revision traffic separately from deploy.
	if service.NoTraffic || service.TrafficPercent <= 0 {
		return ""
	}
	if service.TrafficPercent == 100 {
		return strings.Join([]string{
			"gcloud", "run", "services", "update-traffic", shellQuote(service.Name),
			"--project", shellQuote(cfg.ProjectID),
			"--region", shellQuote(cfg.Region),
			"--platform", "managed",
			"--to-latest",
		}, " ")
	}
	return strings.Join([]string{
		"gcloud", "run", "services", "update-traffic", shellQuote(service.Name),
		"--project", shellQuote(cfg.ProjectID),
		"--region", shellQuote(cfg.Region),
		"--platform", "managed",
		fmt.Sprintf("--to-latest=%d", service.TrafficPercent),
	}, " ")
}

func appendProbeFlags(parts []string, prefix string, probe *Probe) []string {
	if probe == nil {
		return parts
	}
	probeType := probe.Type
	if probeType == "" {
		probeType = "grpc"
	}
	switch probeType {
	case "http":
		parts = append(parts, fmt.Sprintf("--%s-probe-http-path", prefix), shellQuote(probe.Path))
	case "grpc":
		parts = append(parts, fmt.Sprintf("--%s-probe-grpc-port", prefix), strconv.Itoa(probe.Port))
	}
	if probe.InitialDelaySeconds > 0 {
		parts = append(parts, fmt.Sprintf("--%s-probe-initial-delay", prefix), fmt.Sprintf("%ds", probe.InitialDelaySeconds))
	}
	if probe.PeriodSeconds > 0 {
		parts = append(parts, fmt.Sprintf("--%s-probe-period", prefix), fmt.Sprintf("%ds", probe.PeriodSeconds))
	}
	if probe.TimeoutSeconds > 0 {
		parts = append(parts, fmt.Sprintf("--%s-probe-timeout", prefix), fmt.Sprintf("%ds", probe.TimeoutSeconds))
	}
	if probe.FailureThreshold > 0 {
		parts = append(parts, fmt.Sprintf("--%s-probe-failure-threshold", prefix), strconv.Itoa(probe.FailureThreshold))
	}
	if probe.SuccessThreshold > 0 {
		parts = append(parts, fmt.Sprintf("--%s-probe-success-threshold", prefix), strconv.Itoa(probe.SuccessThreshold))
	}
	return parts
}

func deployBaseCommand(cfg Config, service Service) []string {
	return []string{
		deploySurface(service), shellQuote(service.Name),
		"--project", shellQuote(cfg.ProjectID),
		"--region", shellQuote(cfg.Region),
		"--platform", "managed",
		"--image", shellQuote(service.Image),
		"--port", strconv.Itoa(service.Port),
		"--cpu", shellQuote(service.CPU),
		"--memory", shellQuote(service.Memory),
		"--concurrency", strconv.Itoa(service.Concurrency),
		"--min-instances", strconv.Itoa(service.MinInstances),
		"--max-instances", strconv.Itoa(service.MaxInstances),
		"--timeout", shellQuote(service.Timeout),
		"--execution-environment", shellQuote(service.ExecutionEnvironment),
		"--ingress", shellQuote(service.Ingress),
	}
}

func deploySurface(service Service) string {
	if service.StartupProbe != nil || service.LivenessProbe != nil {
		// Probe flags currently live on the beta deploy surface, so switch only when needed.
		return "gcloud beta run deploy"
	}
	return "gcloud run deploy"
}

func appendStringFlag(parts []string, flag string, value string) []string {
	if value == "" {
		return parts
	}
	return append(parts, flag, shellQuote(value))
}

func appendJoinedFlag(parts []string, flag string, values []string) []string {
	if len(values) == 0 {
		return parts
	}
	return append(parts, flag, shellQuote(strings.Join(values, ",")))
}

func appendToggleFlag(parts []string, value *bool, enabledFlag string, disabledFlag string) []string {
	if value == nil {
		return parts
	}
	if *value {
		return append(parts, enabledFlag)
	}
	return append(parts, disabledFlag)
}

func appendFlagIf(parts []string, include bool, flag string) []string {
	if !include {
		return parts
	}
	return append(parts, flag)
}

func appendSecretsFlag(parts []string, service Service) []string {
	if len(service.Secrets) == 0 {
		return parts
	}

	// Secrets are rendered as Cloud Run env-var bindings so the recipe stays stateless.
	values := make([]string, 0, len(service.Secrets))
	for _, secret := range service.SortedSecrets() {
		version := defaultTrimmed(secret.Version, "latest")
		values = append(values, fmt.Sprintf("%s=%s:%s", secret.Target, secret.Secret, version))
	}
	return append(parts, "--update-secrets", shellQuote(strings.Join(values, ",")))
}

func appendKeyValueFlag(parts []string, flag string, keys []string, values map[string]string) []string {
	if len(keys) == 0 {
		return parts
	}

	pairs := make([]string, 0, len(keys))
	for _, key := range keys {
		pairs = append(pairs, fmt.Sprintf("%s=%s", key, values[key]))
	}
	return append(parts, flag, shellQuote(strings.Join(pairs, ",")))
}

func appendCmdState(builder *strings.Builder, title string, command string, env []string, timeout string) {
	builder.WriteString(fmt.Sprintf("  - name: %s\n", yamlScalar(title)))
	builder.WriteString("    cmd.run:\n")
	builder.WriteString(fmt.Sprintf("      - name: %s\n", yamlScalar(command)))
	if len(env) > 0 {
		builder.WriteString("        env:\n")
		for _, entry := range env {
			builder.WriteString(fmt.Sprintf("          - %s\n", yamlScalar(entry)))
		}
	}
	if timeout != "" {
		builder.WriteString(fmt.Sprintf("        timeout: %s\n", yamlScalar(timeout)))
	}
}

func appendDirectoryState(builder *strings.Builder, title string, path string) {
	builder.WriteString(fmt.Sprintf("  - name: %s\n", yamlScalar(title)))
	builder.WriteString("    file.directory:\n")
	builder.WriteString(fmt.Sprintf("      - name: %s\n", yamlScalar(path)))
	builder.WriteString("        makedirs: true\n")
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func yamlScalar(value string) string {
	return strconv.Quote(value)
}
